### ISSUE TITLE
konsultasi

### ISSUE THREAD

**Issue by kakafajar** [kakafajar/websitedonasi#16]
donatur
- [x] donasi pake email #19 
- [x] link konfirmasi nya dikirim lewat email #23 
- [x] kembalikan gambar parallex header #18 

admin
- [x] dashboard tambahin total donasi uang, total donasi jumlah yang success, total donasi jumlah yang pending. #20 
- [x] warning card hapus #20 
- [x] bar perbulan, perminggu, pertahun jumlah donasi uang, dan jumlah donasi orang. #25 
- [x] tambah kolom email ke table transaksi #19
